id = {200: {'cond': 'thunderstorm', 'cond_ru': 'гроза и дождь', 'name': 'thunder'},
201: {'cond': 'thunderstorm', 'cond_ru': 'дождь', 'name': 'thunder'},
202: {'cond': 'thunderstorm', 'cond_ru': 'ливень', 'name': 'thunder'},
210: {'cond': 'light thunderstorm', 'cond_ru': 'гроза', 'name': 'thunder'},
211: {'cond': 'thunderstorm', 'cond_ru': 'гроза', 'name': 'thunder'},
212: {'cond': 'heavy thunderstorm', 'cond_ru': 'сильная гроза', 'name': 'thunder'},
221: {'cond': 'ragged thunderstorm', 'cond_ru': 'гроза', 'name': 'thunder'},
230: {'cond': 'thunderstorm', 'cond_ru': 'гроза', 'name': 'thunder'},
231: {'cond': 'thunderstorm', 'cond_ru': 'гроза', 'name': 'thunder'},
232: {'cond': 'thunderstorm', 'cond_ru': 'гроза', 'name': 'thunder'},
300: {'cond': 'light intensity drizzle', 'cond_ru': 'мелкий дождь', 'name': 'drizzle'},
301: {'cond': 'drizzle', 'cond_ru': 'мелкий дождь', 'name': 'drizzle'},
302: {'cond': 'heavy drizzle', 'cond_ru': 'мелкий дождь', 'name': 'drizzle'},
310: {'cond': 'light drizzle', 'cond_ru': 'мелкий дождь', 'name': 'drizzle'},
311: {'cond': 'drizzle rain', 'cond_ru': 'мелкий дождь', 'name': 'drizzle'},
312: {'cond': 'heavy drizzle rain', 'cond_ru': 'дождь', 'name': 'drizzle'},
313: {'cond': 'shower rain', 'cond_ru': 'ливень', 'name': 'rain'},
314: {'cond': 'heavy shower rain', 'cond_ru': 'ливень', 'name': 'rain'},
321: {'cond': 'shower drizzle', 'cond_ru': 'дождь', 'name': 'drizzle'},
500: {'cond': 'light rain', 'cond_ru': 'легкий дождь', 'name': 'rain'},
501: {'cond': 'moderate rain', 'cond_ru': 'дождь', 'name': 'rain'},
502: {'cond': 'heavy rain', 'cond_ru': 'сильный дождь', 'name': 'rain'},
503: {'cond': 'very heavy rain', 'cond_ru': 'очень сильный дождь', 'name': 'rain'},
504: {'cond': 'extreme rain', 'cond_ru': 'очень сильный дождь', 'name': 'rain'},
511: {'cond': 'freezing rain', 'cond_ru': 'дождь', 'name': 'rain'},
520: {'cond': 'shower rain', 'cond_ru': 'дождь', 'name': 'rain'},
521: {'cond': 'shower rain', 'cond_ru': 'ливень', 'name': 'rain'},
522: {'cond': 'heavy shower rain', 'cond_ru': 'ливень', 'name': 'rain'},
531: {'cond': 'ragged shower rain', 'cond_ru': 'дождь', 'name': 'rain'},
600: {'cond': 'light snow', 'cond_ru': 'слабый снег', 'name': 'snow'},
601: {'cond': 'snow', 'cond_ru': 'снег', 'name': 'snow'},
602: {'cond': 'heavy snow', 'cond_ru': 'сильный снег', 'name': 'snow'},
611: {'cond': 'sleet', 'cond_ru': 'дождь со снегом', 'name': 'snow'},
612: {'cond': 'shower sleet', 'cond_ru': 'дождь со снегом', 'name': 'snow'},
615: {'cond': 'light rain and snow', 'cond_ru': 'дождь со снегом', 'name': 'snow'},
616: {'cond': 'rain and snow', 'cond_ru': 'дождь со снегом', 'name': 'snow'},
620: {'cond': 'light shower snow', 'cond_ru': 'дождь со снегом', 'name': 'snow'},
621: {'cond': 'shower snow', 'cond_ru': 'дождь со снегом', 'name': 'snow'},
622: {'cond': 'heavy shower snow', 'cond_ru': 'дождь со снегом', 'name': 'snow'},
701: {'cond': 'mist', 'cond_ru': 'туман', 'name': 'fog'},
711: {'cond': 'smoke', 'cond_ru': 'туман', 'name': 'fog'},
721: {'cond': 'haze', 'cond_ru': 'туман', 'name': 'fog'},
731: {'cond': 'dust whirls', 'cond_ru': 'песчаная буря', 'name': 'fog'},
741: {'cond': 'fog', 'cond_ru': 'туман', 'name': 'fog'},
751: {'cond': 'sand', 'cond_ru': 'песок', 'name': 'fog'},
761: {'cond': 'dust', 'cond_ru': 'пыль', 'name': 'fog'},
762: {'cond': 'volcanic ash', 'cond_ru': 'вулканический пепел', 'name': 'fog'},
771: {'cond': 'squalls', 'cond_ru': 'вихрь', 'name': 'fog'},
781: {'cond': 'tornado', 'cond_ru': 'торнадо', 'name': 'fog'},
800: {'cond': 'clear sky', 'cond_ru': 'ясно', 'name': 'clear'},
801: {'cond': 'few clouds', 'cond_ru': 'небольшая облачность', 'name': 'cloud'},
802: {'cond': 'scattered clouds', 'cond_ru': 'облачно с прояснениями', 'name': 'cloud'},
803: {'cond': 'broken clouds', 'cond_ru': 'облачно', 'name': 'cloud'},
804: {'cond': 'overcast clouds', 'cond_ru': 'пасмурно', 'name': 'cloud'}}
